FROM openjdk:8u121-jre-alpine
MAINTAINER Yuanhai He <i@bestmike007.com>

RUN apk add --no-cache tzdata && \
    rm -f /etc/localtime && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" >  /etc/timezone && apk del tzdata && date
COPY /srv/build/libs/myzd-wechat-service-0.0.1-SNAPSHOT.jar /srv/myzd-wechat-service.jar
ENTRYPOINT ["java", "-server", "-jar", "/srv/myzd-wechat-service.jar"]